### ISSUE TITLE
Option to skip github releases and changelog updates on dependent bumps?

### ISSUE THREAD

**Issue by noahnu** [tophat/monodeploy#355]
**Is your feature request related to a problem? Please describe.**

Implicit version bumps never have a useful changelog and takes up unnecessary space in changelogs & github releases.

**Describe the solution you'd like**

An option to skip dependent releases (outside of publishing to npm/git).

**Describe alternatives you've considered**

We need to investigate how some other tools handle this.

**Additional context**

**Comment by mcataford** [comment]
I agree on the usefulness of implicit bumps changelogs. If you update a package that is a dependency of most other packages, you just end up with a flood of patch bumps that bury the lede. Having an option to only have "intentional" bumps in the changelog would be beneficial.

re:skipping dependent releases on GH releases though, I'm divided. Depending on how packages are used, those implicit bumps might actually make a big difference in end-user outcome (say the implicit bump fixes a bug that ripples out to the dependents, then you would want to have a release for that).

Perhaps caffeine hasn't kicked in yet and I'm not seeing the big picture on that latter part though. Would love your thoughts. 😅 ☕

**Comment by noahnu** [comment]
Example GitHub release with only a version bump:

![image](https://user-images.githubusercontent.com/1297096/121066584-0d7a3000-c798-11eb-9c51-49049a9c0036.png)

I can't find any other open source projects that do this. So I'm leaning towards not creating releases for the implicit packages (still publishing just not the dedicated release).
