### ISSUE TITLE
Monodeploy modifies pnp file

### ISSUE THREAD

**Issue by Papooch** [tophat/monodeploy#790]
**Describe the bug**

Running `monodeploy` can cause the PnP file to be regenerated, which then breaks subsequent build steps.

- [x] I am interested in contributing a fix.

**To reproduce**

This only happens in _one_ repository of ours and I haven't managed to reproduce it. I'm creating this bug report in hopes that somebody can at least point me to the correct direction where to look at.

In the offending repository, run
1. `yarn`
![image](https://github.com/tophat/monodeploy/assets/46406259/fa32eb01-c899-487e-9ac5-fe3f0b06986a)
2. `git status`
```
nothing to commit, working tree clean
```
3. `yarn monodeploy`
![image](https://github.com/tophat/monodeploy/assets/46406259/bca6506e-ea6d-4b3a-9847-ec856e13fb84)

For some reason, the typescript dependency is removed, which then breaks a subsequent step

**Expected behavior**

If running `yarn` did not result in a PnP file change, neither should running `yarn monodeploy`

- OS: Ubuntu 22.04
- Monodeploy Version: 4.2.0
- Yarn Version: 3.5.0
  - Yarn module linker: pnp
- Node Version: 18.16.0
- Git Version: 2.34.1

**Additional context**
No monodeploy plugins are used

**Comment by noahnu** [comment]
This usually happens due to a mismatch in the version of @yarnpkg/plugin-compat that monodeploy depends on vs. the version embedded in the yarn binary.

We keep monodeploy up to date with the latest released yarn version. I see you're on yarn 3.5.0. I'd recommend trying to update to 3.6.1 first and ensure you're on the latest version of monodeploy.

If that doesn't work, it likely points to a bug we've seen before in yarn's releases where the latest version of plugin-compat doesn't match the latest released binary. In that case, you can set a custom resolution to pin the plugin compat version.

**Comment by Papooch** [comment]
@noahnu Thank you! You were absolutely correct, after updating to yarn 3.6.1, the issue is gone.
